[package]
name = "rust_vercel_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
warp = "0.3"
tokio = { version = "1.37.0", features = ["full"] }
